{
 "title": "Pure Storage FlashBlade system hardware health",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(purefb_info, job)" } },
   {
    "name": "instance",
    "label": "FlashBlade",
    "query": {
     "query": "label_values(purefb_info{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(purefb_hardware_health{instance=~\"$instance\"},controller)"
    }
   },
   {
    "name": "fabricmodule",
    "label": "Fabric Module",
    "query": {
     "query": "label_values(purefb_hardware_health{instance=~\"$instance\",type=\"fm\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "array name",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "purefb_info{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "system events",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(purefb_alerts_open{job=~\"$job\",instance=~\"$instance\"}) by(severity)",
     "legendFormat": "{{ severity }}"
    }
   ]
  },
  {
   "title": "capacity usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{job=~\"$job\", instance=~\"$instance\", space=\"total_physical\", type=\"array\"}) / sum(purefb_array_space_bytes{job=~\"$job\", instance=~\"$instance\", space=\"capacity\", type=\"array\"})"
    }
   ]
  },
  {
   "title": "average iops",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_performance_throughput_iops{job=~\"$job\", instance=~\"$instance\", protocol=\"all\"})",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "average IO latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefb_array_performance_latency_usec{job=~\"$job\",instance=~\"$instance\"}) / 1000"
    }
   ]
  },
  {
   "title": "firmware version",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "purefb_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "data reduction",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_data_reduction_ratio{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "average throughput",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_performance_bandwidth_bytes{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "chassis health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefb_hardware_health{job=\"$job\", instance=\"$instance\", type=\"ch\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "flash blades",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefb_hardware_health{job=\"$job\", instance=\"$instance\", type=\"fb\"})",
     "legendFormat": "{{slot}}"
    }
   ]
  },
  {
   "title": "failed flash blades",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "purefb_hardware_health{job=\"$job\",instance=\"$instance\",type=\"fb\"} != 1",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "failed power supplies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "purefb_hardware_health{job=\"$job\",instance=\"$instance\",type=\"pwr\"} != 1",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "power supply",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(purefb_hardware_health{job=\"$job\",instance=\"$instance\",type=\"pwr\"})\n-\nsum(purefb_hardware_health{job=\"$job\",instance=\"$instance\",type=\"pwr\"})"
    }
   ]
  },
  {
   "title": "Fabric Module $fabricmodule",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "fabricmodule",
   "targets": [
    {}
   ]
  },
  {
   "title": "fabric module health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefb_hardware_health{job=\"$job\", instance=\"$instance\", type=\"fm\"}"
    }
   ]
  },
  {
   "title": "ethernet ports",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefb_hardware_health{job=\"$job\", instance=\"$instance\", type=\"eth\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "failed ethernet ports",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "purefb_hardware_health{job=~\"$job\",instance=~\"$instance\",type=\"eth\"} != 1",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "failed management ports",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "purefb_hardware_health{job=~\"$job\",instance=~\"$instance\",type=\"mgmt_port\"} != 1",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "failed fans",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "purefb_hardware_health{job=~\"$job\",instance=~\"$instance\",type=\"fan\"} != 1",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "management ports",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefb_hardware_health{job=\"$job\",instance=\"$instance\",type=\"mgmt_port\"})\n-\nsum(purefb_hardware_health{job=\"$job\",instance=\"$instance\",type=\"mgmt_port\"})"
    }
   ]
  },
  {
   "title": "fans",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefb_hardware_health{job=\"$job\",instance=\"$instance\",type=\"fan\"})\n-\nsum(purefb_hardware_health{job=\"$job\",instance=\"$instance\",type=\"fan\"})"
    }
   ]
  }
 ]
}