{
 "title": "Pure Storage FlashBlade storage usage detail",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(purefb_info, job)" } },
   {
    "name": "instance",
    "label": "FlashBlade",
    "query": {
     "query": "label_values(purefb_info{job=~\"$job\"}, instance)"
    }
   },
   { "name": "norm_percent", "label": "normalized Percent", "query": "60,70,80,90" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n  <h1>Pure Storage FlashBlade storage usage</h1>\n</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "array name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "purefb_info{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{array_name}}"
    }
   ]
  },
  {
   "title": "capacity usage distribution",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\"}) by (space)",
     "legendFormat": "{{ space }}"
    },
    {
     "expr": "sum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"capacity\",type=\"array\"})\n-\nsum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"total_physical\",type=\"array\"})",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "capacity usage on array",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"total_physical\",type=\"array\"})"
    }
   ]
  },
  {
   "title": "array capacity usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"total_physical\",type=\"array\"})\n/\nsum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"capacity\",type=\"array\"})"
    }
   ]
  },
  {
   "title": "Free based on $norm_percent  % full",
   "type": "stat",
   "description": "Physical free space normalized $norm_percent %\n\npysical_free_space  * normalized_percent / 100 ",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"capacity\",type=\"array\"}) * $norm_percent /100)\n-\nsum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"total_physical\",type=\"array\"})"
    }
   ]
  },
  {
   "title": "Provisioned on Array",
   "type": "stat",
   "description": "Provisioned space.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"capacity\",type=\"array\"}"
    }
   ]
  },
  {
   "title": "data reduction ratio",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_data_reduction_ratio{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "stat",
   "description": "Physical free space (native)",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"capacity\",type=\"array\"})\n-\nsum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"total_physical\",type=\"array\"})"
    }
   ]
  },
  {
   "title": "Free usable",
   "type": "stat",
   "description": "logical free Space normalized.  \n(physical_free_space  * normalized_percent\n/ 100\n) *  data_reduction",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"capacity\",type=\"array\"}) * $norm_percent /100)\n-\nsum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"total_physical\",type=\"array\"})) \n* \navg(purefb_array_space_data_reduction_ratio{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "file systems space usage",
   "type": "table",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(purefb_file_systems_space_bytes{job=~\"$job\",instance=\"$instance\",space=\"total_physical\"}) by (name)",
     "legendFormat": "{{ name}}"
    }
   ]
  },
  {
   "title": "file systems size",
   "type": "table",
   "gridPos": { "h": 16, "w": 7, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(purefb_file_systems_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"virtual\"}) by (name)",
     "legendFormat": "{{ name}}"
    }
   ]
  },
  {
   "title": "file systems data reduction ratio",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(purefb_file_systems_space_data_reduction_ratio{job=~\"$job\",instance=~\"$instance\"}) by (name)",
     "legendFormat": "{{ name}}"
    }
   ]
  }
 ]
}