{
 "title": "Pure Storage FlashBlade storage usage",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(purefb_info, job)" } },
   {
    "name": "instance",
    "label": "FlashBlade",
    "query": {
     "query": "label_values(purefb_info{job=~\"$job\"}, instance)"
    }
   },
   { "name": "norm_percent", "label": "normalized Percent", "query": "60,70,80,90" },
   {
    "name": "array_name",
    "label": "FlashBlade",
    "query": {
     "query": "label_values(purefb_info{job=~\"$job\",instance=~\"$instance\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n  <h1>Pure Storage FlashBlade storage usage</h1>\n</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "array capacity usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"total_physical\"})\n/\nsum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"capacity\"})"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "stat",
   "description": "Physical free space (native)",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"capacity\"})\n-\nsum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"total_physical\"})"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 7, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"capacity\"}) by(instance)\n-\nsum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"total_physical\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Free based on $norm_percent  % full",
   "type": "stat",
   "description": "Physical free space normalized $norm_percent %\n\npysical_free_space  * normalized_percent / 100 ",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"capacity\"}) * $norm_percent /100)\n-\nsum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"total_physical\"})"
    }
   ]
  },
  {
   "title": "4 week capacity delta",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"total_physical\",type=\"array\"}[4w]))"
    }
   ]
  },
  {
   "title": "data reduction ratio",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefb_array_space_data_reduction_ratio{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "capacity usage on array",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{job=\"$job\", instance=~\"$instance\", space=\"total_physical\"})"
    }
   ]
  },
  {
   "title": "Free usable",
   "type": "stat",
   "description": "logical usable free Space normalized.  \n(physical_free_space  * normalized_percent\n/ 100\n) *  data_reduction",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"capacity\",type=\"array\"}) * $norm_percent /100)\n-\nsum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",space=\"total_physical\",type=\"array\"})) \n* \navg(purefb_array_space_data_reduction_ratio{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Provisioned on Array",
   "type": "stat",
   "description": "Provisioned volume space.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  }
 ]
}